# Generated by Django 2.2.7 on 2019-11-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spcategory',
            name='colours',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='spcategory',
            name='size',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
