# Generated by Django 2.2.7 on 2019-11-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_auto_20191116_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='spproduct',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
