# Generated by Django 2.2.7 on 2019-11-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_spproduct_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spsubcategory',
            name='sub_category',
            field=models.CharField(max_length=100),
        ),
    ]
