# Generated by Django 2.2.7 on 2019-11-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_auto_20191116_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spproduct',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='spproduct',
            name='longitude',
        ),
    ]
